spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'
  mapper-locations:
  - classpath:/mybatis/sql/*.xml
#  type-aliases-package: com.rsm.domain

